### ISSUE TITLE
bad sample in test_more

### ISSUE THREAD

**Issue by clonejo** [jo-m/trainbot#14]
Love the big test suite!

(Downloaded from https://trains.jo-m.ch/testdata.zip)

```
2023/11/12 22:25:40 compiled command: ffmpeg -i testdata/set2/train180.mkv -f rawvideo -pix_fmt rgba pipe:
    auto_set0_test.go:81:
        	Error Trace:	/home/clonejo/onlytrains/trainbot/internal/pkg/stitch/auto_set0_test.go:81
        	            				/home/clonejo/onlytrains/trainbot/internal/pkg/stitch/auto_set2_test.go:28
        	Error:      	Should be false
        	Test:       	Test_AutoStitcher_Set2_All
        	Messages:   	expected 1 train(s) but 2 detected: testdata/set2/train180.mkv
```
This video actually has two trains.

I also get failures on set2/train050.mkv and set2/train073.mkv, but those have one train that is just hard to detect.

**Comment by jo-m** [comment]
Indeed, I have removed train180.mkv from the testdata (and renamed another video to be 180) and re-uploaded it.

set2/train050.mkv and set2/train073.mkv are indeed just cases where we do not pass the test suite.
