### ISSUE TITLE
"Killed" (processing from 3MP input sample mp4)

### ISSUE THREAD

**Issue by natevw** [jo-m/trainbot#19]
When processing a small rectangle out of a large video, `trainbot` seems to detect a train but then ends up "Killed." (exit code 137) inside my VM which has 3.8Gi of RAM plus 11Gi of swap added which lets it run slightly longer after starting to process a train. This is with a local sample file which it processes through ffmpeg. The source file is 2304 × 1296 pixels but the crop region is only e.g. 192 x 133.

If I pre-crop the video sample video e.g. `ffmpeg -i sample-rot.mp4 -filter:v "crop=198:133:1403:284" sample-crop.mp4` then I am able to completely process the feed with trainbot. So I wonder if it is somehow trying to keep in memory not just the crop region but all the original (whole) frames too?

**Comment by jo-m** [comment]
We crop the image and then pass around only the cropped image. The original frame is thrown away.
However, I have as slight suspicion for where this could be going wrong. Please check commit 03bcf15b035c385913321b2b87c3f40eaae5a28c to see if that fixes the problem.

**Comment by natevw** [comment]
@jo-m Had a chance to circle back to this this evening. Using the `trainbot-arm64` from the binaries archive on https://github.com/jo-m/trainbot/actions/runs/7159296241 (so the most recent https://github.com/jo-m/trainbot/commit/8afc520a5921451cf4947941b668e64b3960d6ae rather than the original, but afaict the fix should still be in that) —

unfortunately I still get `Killed.` on a large file when used directly.

**Comment by jo-m** [comment]
Hm, any chance you could send me an example video? Can be a link to GDrive via email or similar.

**Comment by natevw** [comment]
Still repros with the latest `trainbot-arm64` from the "binaries" artifact of this latest CI run a few days ago: https://github.com/jo-m/trainbot/actions/runs/8837381153

**Comment by jo-m** [comment]
I tested this on my own machine, with the x86_64 binary from [this CI run](https://github.com/jo-m/trainbot/actions/runs/9149885939).

```
./trainbot \
  --log-pretty \
  --log-level debug \
  --input ./rot.mp4 \
  --rect-x 1403 \
  --rect-y 284 \
  --rect-w 198 \
  --rect-h 133 \
  --px-per-m 19 \
  --min-speed-kph 5 \
  --max-speed-kph 200 \
  --max-frame-count-per-seq 10000
```

The issue is simple - it eats up too much memory, it ate all my 16GiB or RAM and then 16GiB of swap and then crashed by OOM-killer.

So, the options would be
- reduce frame rate, especially if you have slow but long trains
- scale down video

**Comment by natevw** [comment]
> The issue is simple - it eats up too much memory, it ate all my 16GiB or RAM and then 16GiB of swap and then crashed by OOM-killer.

Ah, okay so iiuc it's now no longer a memory "leak" (i.e. unintentional) but just hitting a large amount of memory **expected** to be used now? That would make sense since my own testing is on VMs without much allocated probably shouldn't even both on the Raspberry Pi itself then which is already past its limit just providing the full-size feed itself 😂 

Thanks for looking into this one too, and glad you could get this one closed out even if just something I need to avoid 👍
