### ISSUE TITLE
Feature preview/discussion: Prometheus metrics

### ISSUE THREAD

**Issue by clonejo** [jo-m/trainbot#21]
Hello, 

for better monitoring and adjusting settings i have implemented some Prometheus monitoring and a Grafana dashboard:
![Screenshot 2023-12-18 at 22-44-51 Onlytrains - Dashboards - Grafana](https://github.com/jo-m/trainbot/assets/261803/d7e3b24f-50d2-46fb-9487-eca8697ec416)

https://snapshots.raintank.io/dashboard/snapshot/CprwsU4x2nlsCF7pZYsJMyS0D4YOkkhP

What are your thoughts? I would upstream it, though it does introduce dependencies to https://github.com/prometheus/client_golang/. The added code is pretty small, and the Prometheus endpoint would be off by default.

**Comment by jo-m** [comment]
Yes, I think this would make a lot of sense, as long as the instrumentation is not too intrusive, and cannot block anything.
