### ISSUE TITLE
Two trains in one image

### ISSUE THREAD

**Issue by yngndrw** [jo-m/trainbot#3]
I was scrolling through trying to find the longest train and I found [a pair of trains recorded as 587m](https://trains.jo-m.ch/#/trains/6358).
![A pair of trains](https://trains.jo-m.ch/data/blobs/train_20230510_070412.254_+01:00.jpg)

Looking at the animation, it appears that the two trains passed in opposite directions. They did not overlap, but were quite close to each other.
![A pair of trains passing in opposite directions](https://trains.jo-m.ch/data/blobs/train_20230510_070412.254_+01:00.gif)

For some reason, the image stitching algorithm put them both together as one train and also stitched the second train in the wrong direction.

**Comment by jo-m** [comment]
Yes, unfortunately there is not much that can be done with the current algorithm.
