### ISSUE TITLE
Alignement

### ISSUE THREAD

**Issue by ErikLambrechts** [jo-m/trainbot#5]
Thanks for sharing this fun project.

Could it be possible that the camera is not perfectly aligned with the track? I noticed some jagged features on the stitch lines 
![image](https://github.com/jo-m/trainbot/assets/18344928/8632dde4-15c3-488d-955e-5a6fb651be81) 
It looks like something that could be solved in hardware or software.

**Comment by jo-m** [comment]
Yes, well possible. The Hardware setup of the camera is not very sophisticated, and it is not easy to adjust it 100% perfectly.
